# 数据操作

## 创建张量

In [1]:
import torch

In [2]:
#创建张量
x=torch.arange(12)
print("一维度张量：",x)
#查看张量的形状
print("张量的大小:",x.shape)
#查看张量的元素数量
print("属性个数:",x.numel())

一维度张量： tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
张量的大小: torch.Size([12])
属性个数: 12


改变张量的形状而不改变元素的数量和元素值，我们可以调用**reshape**函数

In [3]:
#转为二维的张量
X=x.reshape(3,4)  
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


使用0、全1、其他常量或者从特定分布中随机采样的数字

In [4]:
#创建一个三维全0张量
x=torch.zeros((2,3,4))
print(x)
#全1
x=torch.ones((2,3,4))
print(x)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


创建特定值的张量

In [5]:
torch.tensor([[1,2,3],[3,4,5],[4,5,6]])  #二维张量

tensor([[1, 2, 3],
        [3, 4, 5],
        [4, 5, 6]])

In [6]:
torch.tensor([[[1,2,3],[3,4,5],[4,5,6]]])  #三维张量

tensor([[[1, 2, 3],
         [3, 4, 5],
         [4, 5, 6]]])

## 标准运算
常见的标准运算符（+、-、*、/、**）

In [7]:
x=torch.tensor([1,2,3,4])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([3, 4, 5, 6]),
 tensor([-1,  0,  1,  2]),
 tensor([2, 4, 6, 8]),
 tensor([0.5000, 1.0000, 1.5000, 2.0000]),
 tensor([ 1,  4,  9, 16]))

In [8]:
torch.exp(x)  #指数运算

tensor([ 2.7183,  7.3891, 20.0855, 54.5981])

## 连接张量

In [9]:
x=torch.arange(12,dtype=torch.float32).reshape((3,4))
y=torch.tensor([[2,3,4,5],[2,3,4,5],[4,3,2,4]])
#张量相乘
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  3.,  4.,  5.],
         [ 2.,  3.,  4.,  5.],
         [ 4.,  3.,  2.,  4.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  3.,  4.,  5.],
         [ 4.,  5.,  6.,  7.,  2.,  3.,  4.,  5.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  4.]]))

求和

In [10]:
x.sum()

tensor(66.)

## 张量的广播机制

In [11]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
print(a,b)

tensor([[0],
        [1],
        [2]]) tensor([[0, 1]])


In [12]:
#将某一个张量改为相同的维度
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 元素访问

In [13]:
x=torch.arange(12).reshape((3,4))
print(x)
x[-1]    #选择最后一行

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


tensor([ 8,  9, 10, 11])

修改元素值

In [14]:
x[0,]=12  #将第一行的元素全部修改为12
x

tensor([[12, 12, 12, 12],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])