# Max-Pooling
与卷积层类似，汇聚层运算符由一个固定形状的窗口组成，该窗口根据其步幅大小在输入的所有区域上滑动，为固定形状窗口（有时称为汇聚窗口）遍历的每个位置计算一个输出。 然而，不同于卷积层中的输入与卷积核之间的互相关计算，汇聚层不包含参数。 相反，池运算是确定性的，我们通常计算汇聚窗口中所有元素的最大值或平均值。这些操作分别称为最大汇聚层（maximum pooling）和平均汇聚层（average pooling）。

<img src="pic\17.jpg" width="500"/>

在下面的代码中的pool2d函数，我们实现汇聚层的前向传播。 然而，这里我们没有卷积核，输出为输入中每个区域的最大值或平均值。

In [10]:
import torch 

In [11]:
def pooling(x,pool_size,mode="max"):
    p_h,p_w=pool_size
    y=torch.zeros(x.shape[0]-p_h+1,x.shape[1]-p_w+1)
    #这里的stride=1
    for i in range(y.shape[0]):
        for j in range(y.shape[1]):
            if mode=="max":
                y[i,j]=x[i:i+p_h,j:j+p_w].max()
            elif mode=="avg":
                y[i,j]=x[i:i+p_h,j:j+p_w].mean()
    return y

In [12]:
x=torch.tensor([[0,1,2],[3,4,5],[6,7,8]])
pooling(x,(2,2))

tensor([[4., 5.],
        [7., 8.]])

# 填充和步幅
与卷积层一样，汇聚层也可以改变输出形状。和以前一样，我们可以通过填充和步幅以获得所需的输出形状。 下面，我们用深度学习框架中内置的二维最大汇聚层，来演示汇聚层中填充和步幅的使用。 我们首先构造了一个输入张量X，它有四个维度，其中样本数和通道数都是1。

In [13]:
x = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
x

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

默认情况下，深度学习框架中的步幅与汇聚窗口的大小相同。 因此，如果我们使用形状为(3, 3)的汇聚窗口，那么默认情况下，我们得到的步幅形状为(3, 3)。

In [14]:
pool2d = torch.nn.MaxPool2d(3)
x,pool2d(x)

(tensor([[[[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]]]]),
 tensor([[[[10.]]]]))

填充和步幅可以手动设定。

In [15]:
pool2d =torch.nn.MaxPool2d(3,padding=1,stride=2)
x,pool2d(x)

(tensor([[[[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]]]]),
 tensor([[[[ 5.,  7.],
           [13., 15.]]]]))

# 多个通道
在处理多通道输入数据时，汇聚层在每个输入通道上单独运算，而不是像卷积层一样在通道上对输入进行汇总。 这意味着汇聚层的输出通道数与输入通道数相同。 下面，我们将在通道维度上连结张量X和X + 1，以构建具有2个通道的输入

In [16]:
x= torch.cat((x,x+1),1)
x

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [19]:
pool2d=torch.nn.MaxPool2d(3,padding=1,stride=2)
pool2d(x)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])