In [3]:
import torch 

# 参数管理
我们首先关注具有单隐藏层的多层感知机

In [4]:
net=torch.nn.Sequential(
    torch.nn.Linear(4,8),
    torch.nn.ReLU(),
    torch.nn.Linear(8,1)
)
x=torch.rand(2,4)
net(x)

tensor([[-0.4211],
        [-0.3499]], grad_fn=<AddmmBackward0>)

## 参数访问

In [7]:
#第一层参数
print(net[0].state_dict())
#第三层参数
print(net[2].state_dict())

OrderedDict([('weight', tensor([[ 2.3414e-01, -7.2474e-02, -2.2102e-01, -1.2125e-01],
        [ 1.7359e-01,  2.4657e-01, -3.6089e-01,  2.1554e-01],
        [-3.6036e-01, -1.2698e-01,  2.5537e-02, -2.4244e-01],
        [-4.7073e-01, -1.1169e-01, -2.4766e-04,  1.5903e-02],
        [ 3.3044e-02, -4.8089e-01,  2.2614e-01, -7.6773e-02],
        [-3.7510e-01,  3.6134e-01,  2.4130e-01,  4.3169e-02],
        [-3.4710e-01,  4.6741e-01, -2.9292e-01,  1.0398e-01],
        [-4.7008e-01,  4.1097e-01,  1.9308e-02,  3.0713e-01]])), ('bias', tensor([-0.0068,  0.1506,  0.0244, -0.3184,  0.2109,  0.2163,  0.0858, -0.1886]))])
OrderedDict([('weight', tensor([[ 0.0171, -0.2248,  0.2709,  0.1348,  0.3504, -0.2684, -0.1596,  0.2174]])), ('bias', tensor([-0.3127]))])


## 目标参数

In [10]:
print(type(net[2].bias))
print(net[2].bias)  
print(net[2].bias.data)

<class 'torch.nn.parameter.Parameter'>
Parameter containing:
tensor([-0.3127], requires_grad=True)
tensor([-0.3127])


In [11]:
print(net[2].weight.grad)  #访问梯度

None


## 一次性访问全部参数

In [17]:
#访问第一层
print(*[(name,param.shape) for name,param in net[0].named_parameters()])
#访问全部的参数
print(*[(name,param.shape) for name,param in net.named_parameters()])

('weight', torch.Size([8, 4])) ('bias', torch.Size([8]))
('0.weight', torch.Size([8, 4])) ('0.bias', torch.Size([8])) ('2.weight', torch.Size([1, 8])) ('2.bias', torch.Size([1]))


## 内置初始化参数

In [28]:
def init_normal(m):
    if type(m)==torch.nn.Linear:  #是否是全连接层
        torch.nn.init.normal_(m.weight,mean=0,std=0.01),  #初始化偏置w
        torch.nn.init.zeros_(m.bias)  #初始化偏置为0

net.apply(init_normal)  #函数嵌套
net[0].weight.data,net[0].bias.data

(tensor([[ 0.0013,  0.0038,  0.0100, -0.0030],
         [-0.0276,  0.0015,  0.0080, -0.0246],
         [ 0.0146,  0.0063,  0.0008,  0.0023],
         [-0.0010,  0.0108,  0.0186,  0.0226],
         [-0.0007, -0.0010, -0.0082, -0.0126],
         [-0.0151,  0.0064,  0.0043, -0.0083],
         [-0.0150, -0.0160,  0.0064, -0.0013],
         [ 0.0076,  0.0134, -0.0056,  0.0052]]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0.]))