# 1 线性代数的实现

## 1.1 标量

In [1]:
import torch

x=torch.tensor(3)
y=torch.tensor(4)
x+y,x-y,x*y,x**y

(tensor(7), tensor(-1), tensor(12), tensor(81))

## 1.2 向量
    一维张量

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

## 1.3 长度、维度、形状

In [4]:
len(x),x.shape

(4, torch.Size([4]))

## 1.4 创建矩阵

In [5]:
a=torch.arange(20).reshape((4,5))
a

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [7]:
a.T  #转置

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

## 1.5 张量的性质

In [10]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

## 1.6 降维

In [11]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [12]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

我们还可以指定张量沿哪一个轴来通过求和降低维度。 以矩阵为例，为了通过求和所有行的元素来降维（轴0），我们可以在调用函数时指定axis=0。 由于输入矩阵沿0轴降维以生成输出向量，因此输入轴0的维数在输出形状中消失。

In [13]:
A_sum_axis0 = A.sum(axis=0)  #沿着y轴向上求和
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

计算平均值

In [16]:
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

同样，计算平均值的函数也可以沿指定轴降低张量的维度。

In [17]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

## 1.7 点积

In [18]:
y = torch.ones(4, dtype = torch.float32)  #向量的点积
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

## 1.8 矩阵乘法

In [19]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

## 1.9 范数
    向量元素平方和的平方根

In [20]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)