# 案例：泰坦尼克号乘客⽣存预测
## 学习目标
* 通过案例进⼀步掌握决策树算法api的具体使⽤

In [74]:
import numpy as np 
import pandas as pd
from sklearn.impute import SimpleImputer  #处理缺失值
from sklearn.model_selection import train_test_split
data=pd.read_csv(r"D:\program_Lab_Report\machine_learning\100day\code\5_决策树\泰塔尼克号.csv")
'''确定特征值'''
x=data.iloc[:,[2,4,5,]].values
y=data.iloc[:,1].values
'''处理缺失值'''
#用均值代替缺失值
imputer=SimpleImputer(strategy="mean")  #用均值替代缺失值
x[:,[0,2]]=imputer.fit_transform(x[:,[0,2]])
'''文本数据数值化'''
#由于文本数据只有female和male，所以本项目将其分为0和1
for item in x:
    if item[1]=='male':
        item[1]=1
    if item[1]=='female':
        item[1]=0
'''数据划分'''
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print(x_train)

[[1.0 1 54.0]
 [3.0 1 13.0]
 [3.0 1 28.0]
 ...
 [3.0 1 25.0]
 [3.0 1 29.881137667304014]
 [3.0 1 29.881137667304014]]


## 模型训练
    sklearn.tree.DecisionTreeClassifier(criterion=’gini’, max_depth=None,random_state=None)
* criterion
    * 特征选择标准
    * "gini"或者"entropy"，前者代表基尼系数，后者代表信息增益。⼀默认"gini"，即CART算法。

* min_samples_split
    * 内部节点再划分所需最⼩样本数
    * 这个值限制了⼦树继续划分的条件，如果某节点的样本数少于min_samples_split，则不会继续再尝试选择最优特征来进⾏划分。 默认是2.如果样本量不⼤，不需要管这个值。如果样本量数量级⾮常⼤，则推荐增⼤这个值。我之前的⼀个项⽬例⼦，有⼤概10万样本，建⽴决策树时，我选择了min_samples_split=10。可以作为参考。

* min_samples_leaf
    * 叶⼦节点最少样本数
    * 这个值限制了叶⼦节点最少的样本数，如果某叶⼦节点数⽬⼩于样本数，则会和兄弟节点⼀起被剪枝。默认是1,可以输⼊最少的样本数的整数，或者最少样本数占样本总数的百分⽐。如果样本量不⼤，不需要管这个值。如果样本量数量级⾮常⼤，则推荐增⼤这个值。之前的10万样本项⽬使⽤min_samples_leaf的值为5，仅供参考。
* max_depth
    * 决策树最⼤深度
    * 决策树的最⼤深度，默认可以不输⼊，如果不输⼊的话，决策树在建⽴⼦树的时候不会限制⼦树的深度。⼀般来说，数据少或者特征少的时候可以不管这个值。如果模型样本量多，特征也多的情况下，推荐限制这个最⼤深度，具体的取值取决于数据的分布。常⽤的可以取值10-100之间

In [75]:
from sklearn.tree import DecisionTreeClassifier
dc=DecisionTreeClassifier(criterion='entropy',max_depth=6)
dc.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=6, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

## 模型评估

In [76]:
#测试集
test_prd=dc.predict(x_test)

test_score=dc.score(x_test,y_test)
print(test_score)

0.8664122137404581


## 决策树可视化
* 网址http://webgraphviz.com/

In [77]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz
export_graphviz(dc, out_file=r"tree.dot", feature_names=['age', 'pclass','sex'])